### ISSUE TITLE
How an I access the data

### ISSUE THREAD

**Issue by nanless** [masakhane-io/bibleTTS#2]
Hi, I'm expressed by your excellent work, but I can't find the access to the data, since I really want to make use of it. Looking forward to your apply

**Comment by esalesky** [comment]
The data should be posted in the next couple days, we will respond here with the link when it's up!

**Comment by esalesky** [comment]
Hi! The data is now public on OpenSLR: [http://www.openslr.org/129/](http://www.openslr.org/129/)
